allowBuilds:
  "@google/genai": true
  "@mongodb-js/zstd": true
  "@sentry/cli": true
  cbor-extract: false
  esbuild: true
  node-liblzma: true
  protobufjs: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
overrides:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: 4.1.10
patchedDependencies:
  "@mastra/daytona@0.6.0": patches/@mastra__daytona@0.6.0.patch
packageExtensions:
  "@daytonaio/sdk@*":
    dependencies:
      tslib: ^2.8.1
  "@opentelemetry/sdk-node@0.207.0":
    dependencies:
      "@opentelemetry/context-async-hooks": 2.2.0
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
