allowBuilds:
  "@google/genai": true
  "@mongodb-js/zstd": true
  "@sentry/cli": true
  cbor-extract: false
  node-liblzma: true
  protobufjs: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
overrides:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: 4.1.10
patchedDependencies:
  "@earendil-works/pi-ai@0.83.0": patches/@earendil-works__pi-ai@0.83.0.patch
  "@flue/vite@2.0.2": patches/@flue__vite@2.0.2.patch
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
